#pragma once

#define APPLICATION_VERSION_MAJOR 0
#define APPLICATION_VERSION_MINOR 1
#define APPLICATION_VERSION_PATCH 0
#define APPLICATION_VERSION_STR "0.1.0"

#define APPLICATION_VERSION VK_MAKE_VERSION(APPLICATION_VERSION_MAJOR, APPLICATION_VERSION_MINOR, APPLICATION_VERSION_PATCH)
#define APPLICATION_NAME "App"

#define ENGINE_VERSION VK_MAKE_VERSION(0, 1, 0)
#define ENGINE_NAME "Sandbox"